replicaCount: 1

image:
  repository: ghcr.io/amayabdaniel/wavekube
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: wavekube-controller

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

leaderElection:
  enabled: true

metrics:
  enabled: true
  port: 8080

healthProbe:
  port: 8081
