//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GNodeB) DeepCopyInto(out *GNodeB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GNodeB) DeepCopy() *GNodeB {
	if in == nil { return nil }
	out := new(GNodeB)
	in.DeepCopyInto(out)
	return out
}

func (in *GNodeB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *GNodeBList) DeepCopyInto(out *GNodeBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GNodeB, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *GNodeBList) DeepCopy() *GNodeBList {
	if in == nil { return nil }
	out := new(GNodeBList)
	in.DeepCopyInto(out)
	return out
}

func (in *GNodeBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *GNodeBSpec) DeepCopyInto(out *GNodeBSpec) {
	*out = *in
	out.GPUResources = in.GPUResources
	out.PHYConfig = in.PHYConfig
	out.Network = in.Network
}

func (in *GNodeBSpec) DeepCopy() *GNodeBSpec {
	if in == nil { return nil }
	out := new(GNodeBSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GNodeBStatus) DeepCopyInto(out *GNodeBStatus) {
	*out = *in
	if in.GPUStatus != nil {
		in, out := &in.GPUStatus, &out.GPUStatus
		*out = make([]GPUInstanceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
	out.Metrics = in.Metrics
}

func (in *GNodeBStatus) DeepCopy() *GNodeBStatus {
	if in == nil { return nil }
	out := new(GNodeBStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GPUResourceSpec) DeepCopy() *GPUResourceSpec {
	if in == nil { return nil }
	out := new(GPUResourceSpec)
	*out = *in
	return out
}

func (in *GPUInstanceStatus) DeepCopy() *GPUInstanceStatus {
	if in == nil { return nil }
	out := new(GPUInstanceStatus)
	*out = *in
	return out
}

func (in *PHYConfig) DeepCopy() *PHYConfig {
	if in == nil { return nil }
	out := new(PHYConfig)
	*out = *in
	return out
}

func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil { return nil }
	out := new(NetworkConfig)
	*out = *in
	return out
}

func (in *RANMetrics) DeepCopy() *RANMetrics {
	if in == nil { return nil }
	out := new(RANMetrics)
	*out = *in
	return out
}

func (in *RANPipeline) DeepCopyInto(out *RANPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RANPipeline) DeepCopy() *RANPipeline {
	if in == nil { return nil }
	out := new(RANPipeline)
	in.DeepCopyInto(out)
	return out
}

func (in *RANPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *RANPipelineList) DeepCopyInto(out *RANPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RANPipeline, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *RANPipelineList) DeepCopy() *RANPipelineList {
	if in == nil { return nil }
	out := new(RANPipelineList)
	in.DeepCopyInto(out)
	return out
}

func (in *RANPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *RANPipelineSpec) DeepCopy() *RANPipelineSpec {
	if in == nil { return nil }
	out := new(RANPipelineSpec)
	*out = *in
	out.Resources = in.Resources
	return out
}

func (in *RANPipelineStatus) DeepCopyInto(out *RANPipelineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *RANPipelineStatus) DeepCopy() *RANPipelineStatus {
	if in == nil { return nil }
	out := new(RANPipelineStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PipelineResources) DeepCopy() *PipelineResources {
	if in == nil { return nil }
	out := new(PipelineResources)
	*out = *in
	return out
}

func (in *RANSecurityPolicy) DeepCopyInto(out *RANSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RANSecurityPolicy) DeepCopy() *RANSecurityPolicy {
	if in == nil { return nil }
	out := new(RANSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *RANSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *RANSecurityPolicyList) DeepCopyInto(out *RANSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RANSecurityPolicy, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *RANSecurityPolicyList) DeepCopy() *RANSecurityPolicyList {
	if in == nil { return nil }
	out := new(RANSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *RANSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *RANSecurityPolicySpec) DeepCopyInto(out *RANSecurityPolicySpec) {
	*out = *in
	if in.AllowedRegistries != nil {
		in, out := &in.AllowedRegistries, &out.AllowedRegistries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *RANSecurityPolicySpec) DeepCopy() *RANSecurityPolicySpec {
	if in == nil { return nil }
	out := new(RANSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RANSecurityPolicyStatus) DeepCopyInto(out *RANSecurityPolicyStatus) {
	*out = *in
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]SecurityViolation, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) }
	}
}

func (in *RANSecurityPolicyStatus) DeepCopy() *RANSecurityPolicyStatus {
	if in == nil { return nil }
	out := new(RANSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SecurityViolation) DeepCopy() *SecurityViolation {
	if in == nil { return nil }
	out := new(SecurityViolation)
	*out = *in
	return out
}
